project:
  type: website
  
website:
  navbar:
    logo: "/images/logos/Panorama.png"
    logo-alt: "PQNA"
    search: false
  
  page-footer:
    left: "Site créé avec [Quarto](https://quarto.org/)"
    center: "©CEREMA"
    background: light
    right: 
      - icon: linkedin
        href: https://fr.linkedin.com/company/cerema
      - icon: twitter-x 
        href: https://x.com/ceremacom
      - icon: youtube
        href: https://www.youtube.com/@cerema3139

format:
  html:
    theme: cosmo
    page-layout: custom
    css: styles.css
    





